//
//gRPC declaration
//
//compile python mapping with:
//pip3 install grpcio-tools
//python3 -m grpc_tools.protoc -I. --python_out=. --pyi_out=. --grpc_python_out=. registry.proto
//
//compile go mapping with:
//apt install protobuf-compiler
//go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
//protoc --go-grpc_out=./ --go_out=./ filename

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: logger.proto

package logger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RegLogger_StartRequest_FullMethodName = "/RegLogger/StartRequest"
	RegLogger_EndRequest_FullMethodName   = "/RegLogger/EndRequest"
)

// RegLoggerClient is the client API for RegLogger service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RegLoggerClient interface {
	StartRequest(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogID, error)
	EndRequest(ctx context.Context, in *EndReq, opts ...grpc.CallOption) (*LogStatus, error)
}

type regLoggerClient struct {
	cc grpc.ClientConnInterface
}

func NewRegLoggerClient(cc grpc.ClientConnInterface) RegLoggerClient {
	return &regLoggerClient{cc}
}

func (c *regLoggerClient) StartRequest(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (*LogID, error) {
	out := new(LogID)
	err := c.cc.Invoke(ctx, RegLogger_StartRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *regLoggerClient) EndRequest(ctx context.Context, in *EndReq, opts ...grpc.CallOption) (*LogStatus, error) {
	out := new(LogStatus)
	err := c.cc.Invoke(ctx, RegLogger_EndRequest_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegLoggerServer is the server API for RegLogger service.
// All implementations must embed UnimplementedRegLoggerServer
// for forward compatibility
type RegLoggerServer interface {
	StartRequest(context.Context, *LogRequest) (*LogID, error)
	EndRequest(context.Context, *EndReq) (*LogStatus, error)
	mustEmbedUnimplementedRegLoggerServer()
}

// UnimplementedRegLoggerServer must be embedded to have forward compatible implementations.
type UnimplementedRegLoggerServer struct {
}

func (UnimplementedRegLoggerServer) StartRequest(context.Context, *LogRequest) (*LogID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartRequest not implemented")
}
func (UnimplementedRegLoggerServer) EndRequest(context.Context, *EndReq) (*LogStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EndRequest not implemented")
}
func (UnimplementedRegLoggerServer) mustEmbedUnimplementedRegLoggerServer() {}

// UnsafeRegLoggerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RegLoggerServer will
// result in compilation errors.
type UnsafeRegLoggerServer interface {
	mustEmbedUnimplementedRegLoggerServer()
}

func RegisterRegLoggerServer(s grpc.ServiceRegistrar, srv RegLoggerServer) {
	s.RegisterService(&RegLogger_ServiceDesc, srv)
}

func _RegLogger_StartRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegLoggerServer).StartRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegLogger_StartRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegLoggerServer).StartRequest(ctx, req.(*LogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RegLogger_EndRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EndReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegLoggerServer).EndRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RegLogger_EndRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegLoggerServer).EndRequest(ctx, req.(*EndReq))
	}
	return interceptor(ctx, in, info, handler)
}

// RegLogger_ServiceDesc is the grpc.ServiceDesc for RegLogger service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RegLogger_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "RegLogger",
	HandlerType: (*RegLoggerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartRequest",
			Handler:    _RegLogger_StartRequest_Handler,
		},
		{
			MethodName: "EndRequest",
			Handler:    _RegLogger_EndRequest_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "logger.proto",
}
