version: '3'

services:
  regdb:
    image: postgres:latest
    restart: always
    ports:
      - 7432:5432
    environment:
      - POSTGRES_PASSWORD=dbpassword
      - POSTGRES_DB=registry
      - POSTGRES_USER=registry
    volumes:
      - registry_db:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-q"]

  regadmin:
    restart: always
    container_name: regadmin
    build:
        context: ./admin
    ports:
      - 8088:8088
    links:
       - regdb

  # whois service
  regwhois:
    restart: always
    container_name: regwhois
    build:
        context: ./whois
    ports:
      - 8043:8043
    links:
       - regdb

  # main EPP service
  regcore:
    restart: always
    container_name: regcore
    build:
        context: ./registry
    ports:
      # EPP
      - 8090:8090
      # gRPC
      - 51015:51015
    links:
       - regdb

volumes:
  registry_db:
    driver: local
