# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: registry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eregistry.proto\"\x07\n\x05\x45mpty\"\x1c\n\x07Session\x12\x11\n\tsessionid\x18\x01 \x01(\t\")\n\x06\x44omain\x12\x11\n\tsessionid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1d\n\x06Status\x12\x13\n\x0breturn_code\x18\x01 \x01(\x05\x32\xa2\x01\n\x08Registry\x12!\n\x0bLoginSystem\x12\x06.Empty\x1a\x08.Session\"\x00\x12*\n\x11GetExpiredDomains\x12\x08.Session\x1a\x07.Domain\"\x00\x30\x01\x12\"\n\x0c\x44\x65leteDomain\x12\x07.Domain\x1a\x07.Status\"\x00\x12#\n\x0cLogoutSystem\x12\x08.Session\x1a\x07.Status\"\x00\x42\nZ\x08.;regrpcb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'registry_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010.;regrpc'
  _EMPTY._serialized_start=18
  _EMPTY._serialized_end=25
  _SESSION._serialized_start=27
  _SESSION._serialized_end=55
  _DOMAIN._serialized_start=57
  _DOMAIN._serialized_end=98
  _STATUS._serialized_start=100
  _STATUS._serialized_end=129
  _REGISTRY._serialized_start=132
  _REGISTRY._serialized_end=294
# @@protoc_insertion_point(module_scope)
