// Code generated by protoc-gen-go. DO NOT EDIT.
// source: logger.proto

package logrpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LogRequest struct {
	ServiceID            uint64   `protobuf:"varint,1,opt,name=ServiceID,proto3" json:"ServiceID,omitempty"`
	RequestType          uint32   `protobuf:"varint,2,opt,name=RequestType,proto3" json:"RequestType,omitempty"`
	SessionID            uint64   `protobuf:"varint,3,opt,name=SessionID,proto3" json:"SessionID,omitempty"`
	UserID               uint64   `protobuf:"varint,4,opt,name=UserID,proto3" json:"UserID,omitempty"`
	IsMonitoring         bool     `protobuf:"varint,5,opt,name=IsMonitoring,proto3" json:"IsMonitoring,omitempty"`
	SourceIP             string   `protobuf:"bytes,6,opt,name=SourceIP,proto3" json:"SourceIP,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{0}
}

func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (m *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(m, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetServiceID() uint64 {
	if m != nil {
		return m.ServiceID
	}
	return 0
}

func (m *LogRequest) GetRequestType() uint32 {
	if m != nil {
		return m.RequestType
	}
	return 0
}

func (m *LogRequest) GetSessionID() uint64 {
	if m != nil {
		return m.SessionID
	}
	return 0
}

func (m *LogRequest) GetUserID() uint64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *LogRequest) GetIsMonitoring() bool {
	if m != nil {
		return m.IsMonitoring
	}
	return false
}

func (m *LogRequest) GetSourceIP() string {
	if m != nil {
		return m.SourceIP
	}
	return ""
}

type EndReq struct {
	LogID                uint64   `protobuf:"varint,1,opt,name=LogID,proto3" json:"LogID,omitempty"`
	RequestCode          uint32   `protobuf:"varint,2,opt,name=RequestCode,proto3" json:"RequestCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EndReq) Reset()         { *m = EndReq{} }
func (m *EndReq) String() string { return proto.CompactTextString(m) }
func (*EndReq) ProtoMessage()    {}
func (*EndReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{1}
}

func (m *EndReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EndReq.Unmarshal(m, b)
}
func (m *EndReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EndReq.Marshal(b, m, deterministic)
}
func (m *EndReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EndReq.Merge(m, src)
}
func (m *EndReq) XXX_Size() int {
	return xxx_messageInfo_EndReq.Size(m)
}
func (m *EndReq) XXX_DiscardUnknown() {
	xxx_messageInfo_EndReq.DiscardUnknown(m)
}

var xxx_messageInfo_EndReq proto.InternalMessageInfo

func (m *EndReq) GetLogID() uint64 {
	if m != nil {
		return m.LogID
	}
	return 0
}

func (m *EndReq) GetRequestCode() uint32 {
	if m != nil {
		return m.RequestCode
	}
	return 0
}

type LogID struct {
	LogID                uint64   `protobuf:"varint,1,opt,name=LogID,proto3" json:"LogID,omitempty"`
	ReturnCode           int32    `protobuf:"varint,2,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogID) Reset()         { *m = LogID{} }
func (m *LogID) String() string { return proto.CompactTextString(m) }
func (*LogID) ProtoMessage()    {}
func (*LogID) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{2}
}

func (m *LogID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogID.Unmarshal(m, b)
}
func (m *LogID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogID.Marshal(b, m, deterministic)
}
func (m *LogID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogID.Merge(m, src)
}
func (m *LogID) XXX_Size() int {
	return xxx_messageInfo_LogID.Size(m)
}
func (m *LogID) XXX_DiscardUnknown() {
	xxx_messageInfo_LogID.DiscardUnknown(m)
}

var xxx_messageInfo_LogID proto.InternalMessageInfo

func (m *LogID) GetLogID() uint64 {
	if m != nil {
		return m.LogID
	}
	return 0
}

func (m *LogID) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

type Status struct {
	ReturnCode           int32    `protobuf:"varint,1,opt,name=return_code,json=returnCode,proto3" json:"return_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_d43b7bfc6b6f7b16, []int{3}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetReturnCode() int32 {
	if m != nil {
		return m.ReturnCode
	}
	return 0
}

func init() {
	proto.RegisterType((*LogRequest)(nil), "LogRequest")
	proto.RegisterType((*EndReq)(nil), "EndReq")
	proto.RegisterType((*LogID)(nil), "LogID")
	proto.RegisterType((*Status)(nil), "Status")
}

func init() { proto.RegisterFile("logger.proto", fileDescriptor_d43b7bfc6b6f7b16) }

var fileDescriptor_d43b7bfc6b6f7b16 = []byte{
	// 299 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xbb, 0xdf, 0x6f, 0x9b, 0xa6, 0xd3, 0x7a, 0x59, 0x44, 0x42, 0x11, 0x5c, 0x16, 0x84,
	0x78, 0xd9, 0x83, 0x1e, 0x05, 0x11, 0xad, 0x87, 0x40, 0x05, 0xd9, 0xe8, 0xc5, 0x8b, 0xd4, 0x74,
	0x58, 0x02, 0x92, 0x6d, 0x67, 0x37, 0x42, 0xff, 0x3d, 0xff, 0x32, 0x31, 0x9b, 0xfe, 0x30, 0xe0,
	0xf1, 0x7d, 0xf2, 0xde, 0xcc, 0xcb, 0x0e, 0x4c, 0x3e, 0xac, 0x31, 0x48, 0x6a, 0x45, 0xd6, 0x5b,
	0xf9, 0xc5, 0x00, 0xe6, 0xd6, 0x68, 0x5c, 0xd7, 0xe8, 0x3c, 0x3f, 0x85, 0x51, 0x8e, 0xf4, 0x59,
	0x16, 0x98, 0xcd, 0x12, 0x26, 0x58, 0xda, 0xd7, 0x7b, 0xc0, 0x05, 0x8c, 0x5b, 0xe3, 0xf3, 0x66,
	0x85, 0xc9, 0x3f, 0xc1, 0xd2, 0x23, 0x7d, 0x88, 0x42, 0xde, 0xb9, 0xd2, 0x56, 0xd9, 0x2c, 0xf9,
	0xbf, 0xcd, 0xb7, 0x80, 0x9f, 0x40, 0xf4, 0xe2, 0x90, 0xb2, 0x59, 0xd2, 0x6f, 0x3e, 0xb5, 0x8a,
	0x4b, 0x98, 0x64, 0xee, 0xd1, 0x56, 0xa5, 0xb7, 0x54, 0x56, 0x26, 0x19, 0x08, 0x96, 0xc6, 0xfa,
	0x17, 0xe3, 0x53, 0x88, 0x73, 0x5b, 0x53, 0x81, 0xd9, 0x53, 0x12, 0x09, 0x96, 0x8e, 0xf4, 0x4e,
	0xcb, 0x5b, 0x88, 0x1e, 0xaa, 0xa5, 0xc6, 0x35, 0x3f, 0x86, 0xc1, 0xdc, 0x9a, 0x5d, 0xf7, 0x20,
	0x0e, 0x7a, 0xdf, 0xdb, 0x65, 0xb7, 0xf7, 0x0f, 0x92, 0x37, 0x6d, 0xee, 0x8f, 0x01, 0x67, 0x30,
	0x26, 0xf4, 0x35, 0x55, 0x6f, 0xc5, 0x76, 0xc0, 0x40, 0x43, 0x40, 0x4d, 0xfe, 0x02, 0xa2, 0xdc,
	0x2f, 0x7c, 0xed, 0xba, 0x56, 0xd6, 0xb5, 0x5e, 0xe6, 0x10, 0x6b, 0x34, 0xa5, 0xf3, 0xb4, 0xe1,
	0xe7, 0x30, 0xc9, 0xfd, 0x82, 0xfc, 0xf6, 0xf9, 0xc7, 0x6a, 0x7f, 0x8b, 0x69, 0xa4, 0x9a, 0xe5,
	0xb2, 0xc7, 0x05, 0x40, 0xf8, 0xbf, 0xc6, 0x34, 0x54, 0x41, 0x4c, 0x87, 0x2a, 0xec, 0x94, 0xbd,
	0x3b, 0x78, 0x8d, 0xd5, 0x35, 0xa1, 0xa1, 0x55, 0xf1, 0x1e, 0x35, 0x97, 0xbd, 0xfa, 0x0e, 0x00,
	0x00, 0xff, 0xff, 0x5c, 0x2a, 0x4d, 0x4c, 0xe9, 0x01, 0x00, 0x00,
}
