-- DROP TABLE Registrar CASCADE;
CREATE TABLE Registrar (
  ID SERIAL CONSTRAINT registrar_pkey PRIMARY KEY,
  Object_id bigint,
  VAT boolean NOT NULL DEFAULT True,
  Handle varchar(255) CONSTRAINT registrar_handle_key UNIQUE NOT NULL,
  Name varchar(1024),
  Country char(2) CONSTRAINT registrar_country_fkey REFERENCES enum_country,
  intpostal varchar(512),
  intaddress jsonb,
  locpostal varchar(512),
  locaddress jsonb,
  legaladdress jsonb,
  taxpayerNumbers varchar(32),
  Telephone jsonb,
  Fax jsonb,
  Email jsonb,
  Auth_notify_email jsonb,
  Notify_Email jsonb,
  Info_Email jsonb,
  Url varchar(1024),
  WWW varchar(255),
  Whois varchar(255),
  System bool default false,
  Regex varchar(30) default NULL,
  epp_requests_limit integer default 0
);

comment on table Registrar is 'Evidence of registrars, who can create or change administered object via register';
comment on column Registrar.ID is 'unique automatically generated identifier';
comment on column Registrar.Handle is 'unique text string identifying registrar, it is generated by system admin when new registrar is created';
comment on column Registrar.Name is 'registrats name';
comment on column Registrar.Country is 'code for country from enum_country table';
comment on column Registrar.Telephone is 'phone number';
comment on column Registrar.Fax is 'fax number';
comment on column Registrar.Email is 'e-mail address';
comment on column Registrar.Url is 'registrars web address';
comment on column Registrar.epp_requests_limit is 'number of epp requests per hour';

-- DROP TABLE RegistrarACL CASCADE;
CREATE TABLE RegistrarACL (
  ID SERIAL CONSTRAINT registraracl_pkey PRIMARY KEY,
  RegistrarID INTEGER NOT NULL CONSTRAINT registraracl_registrarid_fkey REFERENCES Registrar,
  Cert varchar(1024) NOT NULL, -- certificate fingerprint
  Password varchar(64) NOT NULL
);

comment on table RegistrarACL is 'Registrars login information';
comment on column RegistrarACL.Cert is 'certificate fingerprint';
comment on column RegistrarACL.Password is 'login password';

CREATE TABLE registrar_ipaddr_map (
    ID SERIAL CONSTRAINT registrar_ipaddr_map_pkey PRIMARY KEY,
    RegistrarID  INTEGER NOT NULL CONSTRAINT registrar_ipaddr_map_registrarid_fkey REFERENCES registrar ON UPDATE CASCADE ON DELETE CASCADE,
    IpAddr INET NOT NULL -- IP address
);

CREATE TABLE RegistrarInvoice (
  ID SERIAL CONSTRAINT registrarinvoice_pkey PRIMARY KEY,
  RegistrarID INTEGER NOT NULL CONSTRAINT registrarinvoice_registrarid_fkey REFERENCES Registrar, -- registrar id
  Zone integer NOT NULL CONSTRAINT registrarinvoice_zone_fkey REFERENCES Zone,  --  zone for which has registrar an access
  FromDate date NOT NULL , -- date when began registrar work in a zone
  toDate date -- after this date registrar is not allowed to register
);

comment on column RegistrarInvoice.Zone is 'zone for which has registrar an access';
comment on column RegistrarInvoice.FromDate is 'date when began registrar work in a zone';
comment on column RegistrarInvoice.toDate is 'after this date, registrar is not allowed to register';
