name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          
      - name: Install dependencies
        working-directory: ./registry
        run: go get .

      - name: Build Registry
        working-directory: ./registry
        run: go build -v ./...

      - name: Install whois dependencies
        working-directory: ./whois
        run: go get .

      - name: Build Whois
        working-directory: ./whois
        run: go build -v ./...
